# Usa una imagen oficial de Python
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /code

# Copia los archivos necesarios
COPY ./app /code/app
COPY requirements.txt .
COPY ./static /code/static

# Instala dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto de Uvicorn
EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

ENV PYTHONPATH=/app

